@startuml

skinparam defaultFontName Courier

Class User2Group {
    INTEGER ☆ idGroup
    INTEGER ☆ idUser 
}

Class Member {
    INTEGER  ★ idMember       
    VARCHAR  ⚪ MemberName     
    VARCHAR  ⚪ MemberPhotoLink
    DATETIME ⚪ MemberYear     
}

Class Group {
    INTEGER ★ idGroup  
    VARCHAR ⚪ GroupName
    +       events     
    +       user2group 
}

Class User {
    INTEGER ★ idUser  
    VARCHAR ⚪ Email   
    VARCHAR ⚪ UserName
    VARCHAR ⚪ UserPass
    VARCHAR ⚪ VKID    
    +       comment   
    +       group2user
}

Class Task {
    INTEGER ★ idTask    
    INTEGER ☆ idDirector
    INTEGER ☆ idExecutor
    BOOLEAN ⚪ TaskStatus
    VARCHAR ⚪ TaskText  
    +       directors   
    +       executors   
}

Class History {
    INTEGER  ★ idHistory  
    VARCHAR  ⚪ HistoryText
    DATETIME ⚪ HistoryYear
}

Class Comment {
    INTEGER ★ idComment  
    VARCHAR ☆ idWriter   
    VARCHAR ⚪ CommentText
    +       writer       
}

Class Permissions {
    INTEGER ☆ idEvent
    INTEGER ☆ idGroup
}

Class Song {
    INTEGER ★ idSong    
    VARCHAR ⚪ SongText  
    VARCHAR ⚪ SongTitle 
    VARCHAR ⚪ SongWriter
}

Class Event {
    INTEGER  ★ idEvent   
    DATETIME ⚪ EventDate 
    VARCHAR  ⚪ EventGirls
    VARCHAR  ⚪ EventName 
    VARCHAR  ⚪ EventPlace
    INTEGER  ⚪ EventPrice
    VARCHAR  ⚪ EventTime 
    +        groups      
}

User2Group <--o Group: idGroup

User2Group <--o User: idUser

Task <--o User: idExecutor

Task <--o User: idDirector

Comment <--o User: idWriter

Permissions <--o Event: idEvent

Permissions <--o Group: idGroup

right footer generated by sadisplay v0.4.6

@enduml